var card_dict = JSON.parse(
'[ '
+ '  { "name": "OSS Double Agent", "id": "142", "deck": "neutral", "row": "close", "strength": "0", "ability": "hero spy", "filename": "mysterious_elf", "count": "1" }'
+ ', { "name": "Tactical Retreat", "id": "1", "deck": "special", "row": "", "strength": "", "ability": "decoy", "filename": "decoy", "count": "3" }'
+ ', { "name": "Russian Winter", "id": "4", "deck": "weather", "row": "", "strength": "", "ability": "frost", "filename": "frost", "count": "3" }'
+ ', { "name": "General Dwight D. Eisenhower", "id": "139", "deck": "neutral", "row": "close", "strength": "15", "ability": "hero muster", "filename": "ciri", "count": "1", "muster": "Staff Jeep" }'
+ ', { "name": "Clear Skies", "id": "7", "deck": "weather", "row": "", "strength": "", "ability": "clear", "filename": "clear", "count": "3" }'
+ ', { "name": "General\'s Command", "id": "2", "deck": "special", "row": "", "strength": "", "ability": "horn", "filename": "horn", "count": "3" }'
+ ', { "name": "War Correspondent", "id": "11", "deck": "neutral", "row": "close", "strength": "2", "ability": "horn", "filename": "dandelion", "count": "1" }'
+ ', { "name": "Field Surgeon", "id": "", "deck": "neutral", "row": "close", "strength": "5", "ability": "", "filename": "emiel", "count": "1" }'
+ ', { "name": "General George S. Patton", "id": "138", "deck": "neutral", "row": "close", "strength": "15", "ability": "hero muster", "filename": "geralt", "count": "1", "muster": "Staff Jeep" }'
+ ', { "name": "Smoke Screen", "id": "5", "deck": "weather", "row": "", "strength": "", "ability": "fog", "filename": "fog", "count": "3" }'
+ ', { "name": "Air Strike", "id": "3", "deck": "special", "row": "", "strength": "", "ability": "scorch", "filename": "scorch", "count": "3" }'
+ ', { "name": "Heavy Mud", "id": "6", "deck": "weather", "row": "", "strength": "", "ability": "rain", "filename": "rain", "count": "3" }'
+ ', { "name": "Major Dick Winters", "id": "141", "deck": "neutral", "row": "close", "strength": "7", "ability": "hero", "filename": "triss", "count": "1" }'
+ ', { "name": "Captain John Miller", "id": "9", "deck": "neutral", "row": "close", "strength": "6", "ability": "", "filename": "vesemir", "count": "1" }'
+ ', { "name": "Stuka Dive Bomber", "id": "8", "deck": "neutral", "row": "close", "strength": "7", "ability": "scorch_c", "filename": "villen", "count": "1" }'
+ ', { "name": "Jacqueline Cochran", "id": "140", "deck": "neutral", "row": "ranged", "strength": "7", "ability": "hero medic", "filename": "yennefer", "count": "1" }'
+ ', { "name": "Audie Murphy", "id": "10", "deck": "neutral", "row": "close", "strength": "5", "ability": "", "filename": "zoltan", "count": "1" }'
+ ', { "name": "Field Marshal Bernard Montgomery", "id": "", "deck": "neutral", "row": "agile", "strength": "6", "ability": "morale", "filename": "olgierd", "count": "1" }'
+ ', { "name": "Paratrooper Squad", "id": "", "deck": "neutral", "row": "siege", "strength": "2", "ability": "muster", "filename": "gaunter_odimm", "count": "1" }'
+ ', { "name": "Paratrooper Squad - Support", "id": "", "deck": "neutral", "row": "ranged", "strength": "4", "ability": "muster", "filename": "gaunter_odimm_darkness", "count": "3" }'
+ ', { "name": "Inflatable Dummy Tank", "id": "", "deck": "neutral", "row": "ranged", "strength": "0", "ability": "avenger", "filename": "cow", "count": "1" }'
+ ', { "name": "M4 Sherman Tank", "id": "", "deck": "neutral", "row": "close", "strength": "8", "ability": "", "filename": "chort", "count": "0" }'
+ ', { "name": "Franklin D. Roosevelt - Commander in Chief", "id": "5", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_king", "filename": "foltest_silver", "count": "1" }'
+ ', { "name": "Douglas MacArthur - General of the Army", "id": "8", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_lord", "filename": "foltest_gold", "count": "1" }'
+ ', { "name": "Omar Bradley - General of the Army", "id": "6", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_siegemaster", "filename": "foltest_copper", "count": "1" }'
+ ', { "name": "George C. Marshall - General of the Army", "id": "7", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_steelforged", "filename": "foltest_bronze", "count": "1" }'
+ ', { "name": "Chester W. Nimitz - Fleet Admiral", "id": "", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_son", "filename": "foltest_son_of_medell", "count": "1" }'
+ ', { "name": "M2A1 105mm Howitzer", "id": "79", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "ballista", "count": "1" }'
+ ', { "name": "US Ranger Section", "id": "92", "deck": "realms", "row": "close", "strength": "4", "ability": "bond", "filename": "blue_stripes", "count": "3" }'
+ ', { "name": "M12 Gun Motor Carriage", "id": "75", "deck": "realms", "row": "siege", "strength": "8", "ability": "bond", "filename": "catapult_1", "count": "2" }'
+ ', { "name": "101st Airborne Section", "id": "87", "deck": "realms", "row": "ranged", "strength": "5", "ability": "bond", "filename": "crinfrid", "count": "3" }'
+ ', { "name": "B-17 Flying Fortress", "id": "76", "deck": "realms", "row": "ranged", "strength": "6", "ability": "", "filename": "dethmold", "count": "1" }'
+ ', { "name": "US Field Hospital", "id": "88", "deck": "realms", "row": "siege", "strength": "5", "ability": "medic", "filename": "banner_nurse", "count": "1" }'
+ ', { "name": "USS Iowa (BB-61)", "id": "11", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "esterad", "count": "1" }'
+ ', { "name": "General Matthew Ridgway", "id": "10", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "natalis", "count": "1" }'
+ ', { "name": "US Forward Artillery Observer", "id": "98", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege", "count": "1" }'
+ ', { "name": "US Forward Artillery Observer", "id": "99", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege_1", "count": "1" }'
+ ', { "name": "US Forward Artillery Observer", "id": "100", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege_2", "count": "1" }'
+ ', { "name": "P-51 Mustang", "id": "84", "deck": "realms", "row": "ranged", "strength": "5", "ability": "", "filename": "keira", "count": "1" }'
+ ', { "name": "USS Enterprise (CV-6)", "id": "12", "deck": "realms", "row": "ranged", "strength": "10", "ability": "hero", "filename": "philippa", "count": "1" }'
+ ', { "name": "G.I. Infantry", "id": "95", "deck": "realms", "row": "close", "strength": "1", "ability": "bond", "filename": "poor_infantry", "count": "4" }'
+ ', { "name": "OSS Infiltrator", "id": "86", "deck": "realms", "row": "close", "strength": "5", "ability": "spy", "filename": "stennis", "count": "1" }'
+ ', { "name": "National Guard Infantry", "id": "96", "deck": "realms", "row": "close", "strength": "1", "ability": "", "filename": "redania", "count": "1" }'
+ ', { "name": "National Guard Infantry", "id": "97", "deck": "realms", "row": "close", "strength": "1", "ability": "", "filename": "redania_1", "count": "1" }'
+ ', { "name": "M3 Half-track", "id": "91", "deck": "realms", "row": "ranged", "strength": "4", "ability": "", "filename": "sheldon", "count": "1" }'
+ ', { "name": "M4 Sherman Calliope", "id": "81", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "siege_tower", "count": "1" }'
+ ', { "name": "M10 Wolverine", "id": "83", "deck": "realms", "row": "close", "strength": "5", "ability": "", "filename": "siegfried", "count": "1" }'
+ ', { "name": "William J. Donovan", "id": "89", "deck": "realms", "row": "close", "strength": "4", "ability": "spy", "filename": "dijkstra", "count": "1" }'
+ ', { "name": "P-47 Thunderbolt", "id": "85", "deck": "realms", "row": "ranged", "strength": "5", "ability": "", "filename": "sheala", "count": "1" }'
+ ', { "name": "Enigma Decryptionist", "id": "94", "deck": "realms", "row": "siege", "strength": "1", "ability": "spy", "filename": "thaler", "count": "1" }'
+ ', { "name": "B-24 Liberator", "id": "90", "deck": "realms", "row": "ranged", "strength": "4", "ability": "", "filename": "sabrina", "count": "1" }'
+ ', { "name": "General James M. Gavin", "id": "9", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "vernon", "count": "1" }'
+ ', { "name": "Virginia Hall", "id": "82", "deck": "realms", "row": "close", "strength": "5", "ability": "", "filename": "ves", "count": "1" }'
+ ', { "name": "M3 Stuart Light Tank", "id": "93", "deck": "realms", "row": "close", "strength": "2", "ability": "", "filename": "yarpen", "count": "1" }'
+ ', { "name": "M1 155mm Long Tom", "id": "77", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "trebuchet", "count": "1" }'
+ ', { "name": "M1 155mm Long Tom", "id": "78", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "trebuchet_1", "count": "1" }'
+ ', { "name": "Erwin Rommel - Desert Fox", "id": "1", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_imperial", "filename": "emhyr_silver", "count": "1" }'
+ ', { "name": "Gerd von Rundstedt - Field Marshal", "id": "2", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_emperor", "filename": "emhyr_copper", "count": "1" }'
+ ', { "name": "Heinz Guderian - Panzer General", "id": "3", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_whiteflame", "filename": "emhyr_bronze", "count": "1" }'
+ ', { "name": "Erich von Manstein - Field Marshal", "id": "4", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_relentless", "filename": "emhyr_gold", "count": "1" }'
+ ', { "name": "Albert Kesselring - Field Marshal", "id": "", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_invader", "filename": "emhyr_invader_of_the_north", "count": "1" }'
+ ', { "name": "Messerschmitt Bf 109", "id": "68", "deck": "nilfgaard", "row": "ranged", "strength": "2", "ability": "", "filename": "albrich", "count": "1" }'
+ ', { "name": "Junkers Ju 87 Stuka", "id": "52", "deck": "nilfgaard", "row": "ranged", "strength": "6", "ability": "", "filename": "assire", "count": "1" }'
+ ', { "name": "8.8 cm Flak 36", "id": "47", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "", "filename": "black_archer", "count": "1" }'
+ ', { "name": "8.8 cm Flak 36", "id": "48", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "", "filename": "black_archer_1", "count": "1" }'
+ ', { "name": "Panzer IV Tank", "id": "54", "deck": "nilfgaard", "row": "close", "strength": "6", "ability": "", "filename": "cahir", "count": "1" }'
+ ', { "name": "Sd.Kfz. 234/2 Puma", "id": "60", "deck": "nilfgaard", "row": "ranged", "strength": "4", "ability": "", "filename": "cynthia", "count": "1" }'
+ ', { "name": "Wehrmacht Medic", "id": "72", "deck": "nilfgaard", "row": "ranged", "strength": "1", "ability": "medic", "filename": "archer_support", "count": "1" }'
+ ', { "name": "Wehrmacht Medic", "id": "73", "deck": "nilfgaard", "row": "ranged", "strength": "1", "ability": "medic", "filename": "archer_support_1", "count": "1" }'
+ ', { "name": "Focke-Wulf Fw 190", "id": "53", "deck": "nilfgaard", "row": "ranged", "strength": "6", "ability": "", "filename": "fringilla", "count": "1" }'
+ ', { "name": "Karl-Gerät 60cm Mortar", "id": "49", "deck": "nilfgaard", "row": "siege", "strength": "10", "ability": "", "filename": "heavy_zerri", "count": "1" }'
+ ', { "name": "Panzergrenadier Squad", "id": "67", "deck": "nilfgaard", "row": "close", "strength": "3", "ability": "bond", "filename": "imperal_brigade", "count": "4" }'
+ ', { "name": "Tiger II (King Tiger)", "id": "147", "deck": "nilfgaard", "row": "close", "strength": "10", "ability": "hero", "filename": "letho", "count": "1" }'
+ ', { "name": "Field Marshal Walter Model", "id": "148", "deck": "nilfgaard", "row": "close", "strength": "10", "ability": "hero medic", "filename": "menno", "count": "1" }'
+ ', { "name": "StuG III Assault Gun", "id": "64", "deck": "nilfgaard", "row": "close", "strength": "3", "ability": "", "filename": "morteisen", "count": "1" }'
+ ', { "name": "Schwerer Gustav Railway Gun", "id": "149", "deck": "nilfgaard", "row": "siege", "strength": "10", "ability": "hero", "filename": "moorvran", "count": "1" }'
+ ', { "name": "Panzer II Luchs Section", "id": "71", "deck": "nilfgaard", "row": "close", "strength": "2", "ability": "bond", "filename": "nauzicaa_2", "count": "3" }'
+ ', { "name": "Sd.Kfz. 251 Half-track", "id": "66", "deck": "nilfgaard", "row": "ranged", "strength": "3", "ability": "", "filename": "puttkammer", "count": "1" }'
+ ', { "name": "Jagdpanzer IV", "id": "61", "deck": "nilfgaard", "row": "close", "strength": "4", "ability": "", "filename": "rainfarn", "count": "1" }'
+ ', { "name": "Wehrmacht Officer", "id": "56", "deck": "nilfgaard", "row": "ranged", "strength": "5", "ability": "", "filename": "renuald", "count": "1" }'
+ ', { "name": "Nebelwerfer Rocket Artillery", "id": "65", "deck": "nilfgaard", "row": "siege", "strength": "3", "ability": "", "filename": "rotten", "count": "1" }'
+ ', { "name": "Abwehr Agent", "id": "51", "deck": "nilfgaard", "row": "close", "strength": "7", "ability": "spy", "filename": "shilard", "count": "1" }'
+ ', { "name": "15 cm sFH 18 Howitzer", "id": "55", "deck": "nilfgaard", "row": "siege", "strength": "6", "ability": "", "filename": "siege_engineer", "count": "1" }'
+ ', { "name": "Wehrmacht Repair Depot", "id": "74", "deck": "nilfgaard", "row": "siege", "strength": "0", "ability": "medic", "filename": "siege_support", "count": "1" }'
+ ', { "name": "Reinhard Gehlen", "id": "50", "deck": "nilfgaard", "row": "close", "strength": "9", "ability": "spy", "filename": "stefan", "count": "1" }'
+ ', { "name": "Opel Blitz Supply Truck", "id": "69", "deck": "nilfgaard", "row": "ranged", "strength": "2", "ability": "", "filename": "sweers", "count": "1" }'
+ ', { "name": "Tiger I Tank", "id": "150", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "hero", "filename": "tibor", "count": "1" }'
+ ', { "name": "Heinkel He 111", "id": "62", "deck": "nilfgaard", "row": "ranged", "strength": "4", "ability": "", "filename": "vanhemar", "count": "1" }'
+ ', { "name": "Gestapo Spy", "id": "63", "deck": "nilfgaard", "row": "close", "strength": "4", "ability": "spy", "filename": "vattier", "count": "1" }'
+ ', { "name": "Wehrmacht Captain", "id": "70", "deck": "nilfgaard", "row": "close", "strength": "2", "ability": "", "filename": "vreemde", "count": "1" }'
+ ', { "name": "Volkssturm Militia", "id": "58", "deck": "nilfgaard", "row": "close", "strength": "5", "ability": "bond", "filename": "young_emissary", "count": "1" }'
+ ', { "name": "Volkssturm Militia", "id": "59", "deck": "nilfgaard", "row": "close", "strength": "5", "ability": "bond", "filename": "young_emissary_1", "count": "1" }'
+ ', { "name": "Wespe 10.5cm Howitzer", "id": "57", "deck": "nilfgaard", "row": "siege", "strength": "5", "ability": "", "filename": "zerri", "count": "1" }'
+ ', { "name": "Georgy Zhukov - Marshal of the Soviet Union", "id": "134", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_commander", "filename": "eredin_silver", "count": "1" }'
+ ', { "name": "Aleksandr Vasilevsky - Marshal of the Soviet Union", "id": "136", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_bringer_of_death", "filename": "eredin_bronze", "count": "1" }'
+ ', { "name": "Konstantin Rokossovsky - Marshal of the Soviet Union", "id": "137", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_destroyer", "filename": "eredin_gold", "count": "1" }'
+ ', { "name": "Ivan Konev - Marshal of the Soviet Union", "id": "135", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_king", "filename": "eredin_copper", "count": "1" }'
+ ', { "name": "Vasily Chuikov - General of the Army", "id": "", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_treacherous", "filename": "eredin_the_treacherous", "count": "1" }'
+ ', { "name": "Conscript Rifle Squad ", "id": "27", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas", "count": "1" }'
+ ', { "name": "Conscript Rifle Squad ", "id": "28", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas_1", "count": "1" }'
+ ', { "name": "Conscript Rifle Squad ", "id": "29", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas_2", "count": "1" }'
+ ', { "name": "Conscript Rifle Squad- Commander", "id": "15", "deck": "monsters", "row": "siege", "strength": "6", "ability": "muster", "filename": "arachas_behemoth", "count": "1" }'
+ ', { "name": "PPSh-41 SMG Squad", "id": "26", "deck": "monsters", "row": "close", "strength": "4", "ability": "", "filename": "poroniec", "count": "1" }'
+ ', { "name": "Polikarpov Po-2 (Night Witches)", "id": "38", "deck": "monsters", "row": "agile", "strength": "2", "ability": "", "filename": "celaeno_harpy", "count": "1" }'
+ ', { "name": "Yakovlev Yak-3", "id": "36", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "cockatrice", "count": "1" }'
+ ', { "name": "Siberian Shock Infantry", "id": "16", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen", "count": "1" }'
+ ', { "name": "Soviet Guards Infantry", "id": "17", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen_1", "count": "1" }'
+ ', { "name": "Red Army Assault Engineers", "id": "18", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen_2", "count": "1" }'
+ ', { "name": "IS-2 Heavy Tank", "id": "143", "deck": "monsters", "row": "close", "strength": "10", "ability": "hero", "filename": "draug", "count": "1" }'
+ ', { "name": "ML-20 152mm Howitzer", "id": "12", "deck": "monsters", "row": "siege", "strength": "6", "ability": "", "filename": "earth_elemental", "count": "1" }'
+ ', { "name": "Lavochkin La-7", "id": "34", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "endrega", "count": "1" }'
+ ', { "name": "SU-152 Tank Destroyer", "id": "13", "deck": "monsters", "row": "close", "strength": "6", "ability": "", "filename": "fiend", "count": "1" }'
+ ', { "name": "B-4 203mm Howitzer", "id": "14", "deck": "monsters", "row": "siege", "strength": "6", "ability": "", "filename": "fire_elemental", "count": "1" }'
+ ', { "name": "Partisan Saboteurs", "id": "39", "deck": "monsters", "row": "close", "strength": "2", "ability": "", "filename": "fogling", "count": "1" }'
+ ', { "name": "T-34/76 Medium Tank", "id": "19", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "forktail", "count": "1" }'
+ ', { "name": "KV-1 Heavy Tank", "id": "23", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "frightener", "count": "1" }'
+ ', { "name": "Ilyushin Il-2 Sturmovik", "id": "37", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "gargoyle", "count": "1" }'
+ ', { "name": "Penal Battalion (Shtrafbat)", "id": "44", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul", "count": "1" }'
+ ', { "name": "Penal Battalion (Shtrafbat)", "id": "45", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul_1", "count": "1" }'
+ ', { "name": "Penal Battalion (Shtrafbat)", "id": "46", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul_2", "count": "1" }'
+ ', { "name": "BM-13 Katyusha Launcher", "id": "25", "deck": "monsters", "row": "ranged", "strength": "5", "ability": "", "filename": "gravehag", "count": "1" }'
+ ', { "name": "KV-2 Heavy Tank", "id": "21", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "gryffin", "count": "1" }'
+ ', { "name": "Petlyakov Pe-2", "id": "35", "deck": "monsters", "row": "agile", "strength": "2", "ability": "", "filename": "harpy", "count": "1" }'
+ ', { "name": "ISU-152 Heavy SPG", "id": "24", "deck": "monsters", "row": "siege", "strength": "5", "ability": "", "filename": "frost_giant", "count": "1" }'
+ ', { "name": "Vasily Zaytsev", "id": "144", "deck": "monsters", "row": "close", "strength": "10", "ability": "hero", "filename": "imlerith", "count": "1" }'
+ ', { "name": "T-34/85 Medium Tank", "id": "146", "deck": "monsters", "row": "agile", "strength": "8", "ability": "hero morale", "filename": "kayran", "count": "1" }'
+ ', { "name": "Katyusha Rocket Battery", "id": "145", "deck": "monsters", "row": "ranged", "strength": "10", "ability": "hero", "filename": "leshen", "count": "1" }'
+ ', { "name": "Red Army Guardsman", "id": "41", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker", "count": "1" }'
+ ', { "name": "Red Army Guardsman", "id": "42", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker_1", "count": "1" }'
+ ', { "name": "Red Army Guardsman", "id": "43", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker_2", "count": "1" }'
+ ', { "name": "SU-85 Tank Destroyer", "id": "20", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "mighty_maiden", "count": "1" }'
+ ', { "name": "T-34 Tank Regiment - Model 1940", "id": "33", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "bruxa", "count": "1" }'
+ ', { "name": "T-34 Tank Regiment - Model 1941", "id": "30", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "ekkima", "count": "1" }'
+ ', { "name": "T-34 Tank Regiment - Model 1942", "id": "31", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "fleder", "count": "1" }'
+ ', { "name": "T-34 Tank Regiment - Model 1943", "id": "32", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "garkain", "count": "1" }'
+ ', { "name": "T-34 Tank Regiment - T-34-85", "id": "", "deck": "monsters", "row": "close", "strength": "5", "ability": "muster", "filename": "katakan", "count": "1" }'
+ ', { "name": "ISU-122 Tank Destroyer", "id": "22", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "werewolf", "count": "1" }'
+ ', { "name": "Tupolev Tu-2", "id": "40", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "wyvern", "count": "1" }'
+ ', { "name": "SU-100 Tank Destroyer", "id": "", "deck": "monsters", "row": "ranged", "strength": "7", "ability": "scorch_r", "filename": "toad", "count": "1" }'
+ ', { "name": "Hideki Tojo - Prime Minister", "id": "13", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_queen", "filename": "francesca_silver", "count": "1" }'
+ ', { "name": "Isoroku Yamamoto - Grand Admiral", "id": "14", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_beautiful", "filename": "francesca_gold", "count": "1" }'
+ ', { "name": "Tomoyuki Yamashita - General", "id": "15", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_daisy", "filename": "francesca_copper", "count": "1" }'
+ ', { "name": "Jisaburo Ozawa - Vice Admiral", "id": "16", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_pureblood", "filename": "francesca_bronze", "count": "1" }'
+ ', { "name": "Tadamichi Kuribayashi - General", "id": "", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_hope", "filename": "francesca_hope_of_the_aen_seidhe", "count": "1" }'
+ ', { "name": "Type 97 Chi-Ha Tank", "id": "122", "deck": "scoiatael", "row": "agile", "strength": "3", "ability": "", "filename": "ciaran", "count": "1" }'
+ ', { "name": "Type 1 Chi-He Tank", "id": "106", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "barclay", "count": "1" }'
+ ', { "name": "Type 3 Chi-Nu Tank", "id": "102", "deck": "scoiatael", "row": "close", "strength": "6", "ability": "", "filename": "dennis", "count": "1" }'
+ ', { "name": "Type 99 LMG Squad", "id": "121", "deck": "scoiatael", "row": "ranged", "strength": "4", "ability": "", "filename": "dol_archer", "count": "1" }'
+ ', { "name": "Jungle Camouflage Snipers", "id": "107", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry", "count": "1" }'
+ ', { "name": "Jungle Camouflage Snipers", "id": "108", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry_1", "count": "1" }'
+ ', { "name": "Jungle Camouflage Snipers", "id": "109", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry_2", "count": "1" }'
+ ', { "name": "Banzai Charger", "id": "123", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf", "count": "1" }'
+ ', { "name": "Banzai Charger", "id": "124", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf_1", "count": "1" }'
+ ', { "name": "Banzai Charger", "id": "125", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf_2", "count": "1" }'
+ ', { "name": "Yamato-class Battleship", "id": "17", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "eithne", "count": "1" }'
+ ', { "name": "IJA Rifleman", "id": "127", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher", "count": "1" }'
+ ', { "name": "IJA Rifleman", "id": "128", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher_1", "count": "1" }'
+ ', { "name": "IJA Rifleman", "id": "129", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher_2", "count": "1" }'
+ ', { "name": "Type 95 Ha-Go Light Tank", "id": "104", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "filavandrel", "count": "1" }'
+ ', { "name": "IJA Field Nurse", "id": "131", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse", "count": "1" }'
+ ', { "name": "IJA Field Nurse", "id": "132", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse_1", "count": "1" }'
+ ', { "name": "IJA Field Nurse", "id": "133", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse_2", "count": "1" }'
+ ', { "name": "Special Naval Landing Force", "id": "110", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support", "count": "1" }'
+ ', { "name": "Special Naval Landing Force", "id": "111", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support_1", "count": "1" }'
+ ', { "name": "Special Naval Landing Force", "id": "112", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support_2", "count": "1" }'
+ ', { "name": "Mitsubishi A6M Zero", "id": "103", "deck": "scoiatael", "row": "ranged", "strength": "6", "ability": "", "filename": "ida", "count": "1" }'
+ ', { "name": "Nakajima Ki-84 Fighter", "id": "20", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "iorveth", "count": "1" }'
+ ', { "name": "Colonel Yasuyo Yamasaki", "id": "19", "deck": "scoiatael", "row": "close", "strength": "10", "ability": "hero morale", "filename": "isengrim", "count": "1" }'
+ ', { "name": "Defensive Pillbox", "id": "115", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam", "count": "1" }'
+ ', { "name": "Defensive Pillbox", "id": "116", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_1", "count": "1" }'
+ ', { "name": "Defensive Pillbox", "id": "117", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_2", "count": "1" }'
+ ', { "name": "Defensive Pillbox", "id": "118", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_3", "count": "1" }'
+ ', { "name": "Defensive Pillbox", "id": "119", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_4", "count": "1" }'
+ ', { "name": "Admiral Chuichi Nagumo", "id": "101", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "morale", "filename": "milva", "count": "1" }'
+ ', { "name": "Arisaka Rifleman", "id": "130", "deck": "scoiatael", "row": "ranged", "strength": "1", "ability": "", "filename": "riordain", "count": "1" }'
+ ', { "name": "Aichi D3A Val Bomber", "id": "18", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "saskia", "count": "1" }'
+ ', { "name": "Type 89 Knee Mortar", "id": "126", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "", "filename": "toruviel", "count": "1" }'
+ ', { "name": "Type 3 Ka-Chi Amphibious Tank", "id": "120", "deck": "scoiatael", "row": "ranged", "strength": "4", "ability": "", "filename": "vrihedd_cadet", "count": "1" }'
+ ', { "name": "SNLF Infantry Veteran", "id": "113", "deck": "scoiatael", "row": "agile", "strength": "5", "ability": "", "filename": "vrihedd_brigade", "count": "1" }'
+ ', { "name": "SNLF Infantry Veteran", "id": "114", "deck": "scoiatael", "row": "agile", "strength": "5", "ability": "", "filename": "vrihedd_brigade_1", "count": "1" }'
+ ', { "name": "Type 2 Ka-Mi Amphibious Tank", "id": "105", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "yaevinn", "count": "1" }'
+ ', { "name": "SAS Recruit Commando", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "berserker", "filename": "berserker", "count": "1" }'
+ ', { "name": "British Red Cross Nurse", "id": "", "deck": "skellige", "row": "close", "strength": "2", "ability": "medic", "filename": "birna", "count": "1" }'
+ ', { "name": "Churchill Crocodile Tank", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "", "filename": "blueboy", "count": "1" }'
+ ', { "name": "HMS Hood", "id": "", "deck": "skellige", "row": "close", "strength": "10", "ability": "hero muster", "filename": "cerys", "count": "1" }'
+ ', { "name": "Supermarine Spitfire", "id": "", "deck": "skellige", "row": "ranged", "strength": "6", "ability": "", "filename": "brokva_archer", "count": "2" }'
+ ', { "name": "HMS Prince of Wales", "id": "", "deck": "skellige", "row": "ranged", "strength": "6", "ability": "scorch", "filename": "dimun_pirate", "count": "1" }'
+ ', { "name": "HMS Hood - Escort Destroyer", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden", "count": "1" }'
+ ', { "name": "HMS Hood - Escort Destroyer", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden_1", "count": "1" }'
+ ', { "name": "HMS Hood - Escort Destroyer", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden_2", "count": "1" }'
+ ', { "name": "Royal Marine Commando", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "heymaey", "count": "1" }'
+ ', { "name": "Royal Engineers Support", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "tordarroch", "count": "1" }'
+ ', { "name": "Tommies (British Infantry)", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "bond", "filename": "craite_warrior", "count": "3" }'
+ ', { "name": "Cromwell Cruiser Tank", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "donar", "count": "1" }'
+ ', { "name": "Bagpiper Platoon", "id": "", "deck": "skellige", "row": "siege", "strength": "2", "ability": "horn", "filename": "draig", "count": "1" }'
+ ', { "name": "Lord Mountbatten", "id": "", "deck": "skellige", "row": "ranged", "strength": "8", "ability": "hero mardroeme", "filename": "ermion", "count": "1" }'
+ ', { "name": "HMS Vanguard", "id": "", "deck": "skellige", "row": "close", "strength": "11", "ability": "hero", "filename": "hemdall", "count": "0" }'
+ ', { "name": "Avro Lancaster Bomber", "id": "", "deck": "skellige", "row": "ranged", "strength": "10", "ability": "hero", "filename": "hjalmar", "count": "1" }'
+ ', { "name": "Matilda II Infantry Tank", "id": "", "deck": "skellige", "row": "siege", "strength": "4", "ability": "", "filename": "holger", "count": "1" }'
+ ', { "name": "Naval Decoy Q-Ship", "id": "", "deck": "skellige", "row": "close", "strength": "0", "ability": "avenger_kambi", "filename": "kambi", "count": "1" }'
+ ', { "name": "Fairmile D Motor Torpedo Boat", "id": "", "deck": "skellige", "row": "ranged", "strength": "4", "ability": "muster", "filename": "light_longship", "count": "3" }'
+ ', { "name": "Valentine Infantry Tank", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "", "filename": "madmad_lugos", "count": "1" }'
+ ', { "name": "Commando Training", "id": "", "deck": "special", "row": "", "strength": "", "ability": "mardroeme", "filename": "mardroeme", "count": "3" }'
+ ', { "name": "Field Marshal Alan Brooke", "id": "", "deck": "skellige", "row": "agile", "strength": "12", "ability": "morale", "filename": "olaf", "count": "1" }'
+ ', { "name": "Atlantic Storm", "id": "", "deck": "weather", "row": "", "strength": "", "ability": "storm rain fog", "filename": "storm", "count": "3" }'
+ ', { "name": "Sherman Firefly Tank", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "svanrige", "count": "1" }'
+ ', { "name": "SAS Saboteur Squad", "id": "", "deck": "skellige", "row": "close", "strength": "14", "ability": "vildkarrl morale", "filename": "vildkaarl", "count": "0" }'
+ ', { "name": "SBS Assault Team", "id": "", "deck": "skellige", "row": "ranged", "strength": "8", "ability": "vildkarrl bond", "filename": "young_vildkaarl", "count": "0" }'
+ ', { "name": "Crusader Cruiser Tank", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "udalryk", "count": "1" }'
+ ', { "name": "Tribal-class Destroyer", "id": "", "deck": "skellige", "row": "siege", "strength": "6", "ability": "bond", "filename": "war_longship", "count": "3" }'
+ ', { "name": "SAS Recruit Cadet", "id": "", "deck": "skellige", "row": "ranged", "strength": "2", "ability": "berserker", "filename": "young_berserker", "count": "3" }'
+ ', { "name": "Winston Churchill - Prime Minister", "id": "", "deck": "skellige", "row": "leader", "strength": "", "ability": "crach_an_craite", "filename": "crach_an_craite", "count": "0" }'
+ ', { "name": "Bernard Montgomery - Field Marshal", "id": "", "deck": "skellige", "row": "leader", "strength": "", "ability": "king_bran", "filename": "king_bran", "count": "0" }'
+ ', { "name": "Yokosuka MXY-7 Ohka", "id": "", "deck": "scoiatael", "row": "siege", "strength": "8", "ability": "scorch_s", "filename": "schirru", "count": "1" }'
+ ', { "name": "Staff Jeep", "id": "", "deck": "neutral", "row": "close", "strength": "3", "ability": "", "filename": "roach", "count": "1" }'
+ ', { "name": "M2A1 105mm Howitzer", "id": "", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "ballista_1", "count": "1" }'
+ ']'
);
